version: '3'

services:
  db:
    build: database
    container_name: mysql-server
    expose: 
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${ENV_DB_NAME}
      - MYSQL_USER=${ENV_DB_USER}
      - MYSQL_PASSWORD=${ENV_DB_PASSWORD}
    volumes:
      - ${ENV_DB_VOLUME}:/var/lib/mysql  
  app:
    build: tomcat
    container_name: tomcat-server
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    expose:
      - '8080'
    depends_on:
      - db
    links:
      - db
    volumes:
      - ${ENV_APP_VOLUME}:/usr/local/tomcat/webapps/customer     
    networks:
      - webnet
  web:
    build: apache
    ports:
      - '9080:80'
    depends_on:
      - app
    links:
      - app
networks:
  webnet:
