version: '3'

services:
  db:
    image: swarmdb
    container_name: mysql-server
    expose: 
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${ENV_DB_NAME}
      - MYSQL_USER=${ENV_DB_USER}
      - MYSQL_PASSWORD=${ENV_DB_PASSWORD}
    volumes:
      - ${ENV_DB_VOLUME}:/var/lib/mysql  
    networks:
      - webnet
  app:
    image: swarmapp
    container_name: tomcat-server
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
      restart_policy:
        condition: on-failure
    expose:
      - '8080'
    volumes:
      - ${ENV_APP_VOLUME}:/usr/local/tomcat/webapps/customer     
    networks:
      - webnet
  web:
    image: swarmweb
    ports:
      - '9080:80'
    networks:
      - webnet
networks:
  webnet:
